const i18n = {
  en: {
    navGroupExplore: "Explore",
    navGroupCreate: "Create",
    navTools: "Tools",
    themeLight: "Light",
    themeDark: "Dark",
    navPerformance: "Live charts",
    navMedia: "Caption AI",
    navStudio: "Video studio",
    studioEyebrow: "Advanced video studio",
    studioTitle: "Create a complete, luxurious video",
    studioText: "Use the tabs in order: 1) Template, 2) Media, 3) Format, 4) Text, 5) Logo. The timeline below the preview shows each layer — drag the red playhead to scrub. Press Preview to play, then Export to save a real video file.",
    vTabTemplate: "Template",
    vTabMedia: "Media",
    vTabSlides: "Slides",
    vSlidesLabel: "Slide sequence",
    vSlidesHint: "Add multiple slides — each with its own media, headline and duration. They play one after another as a single video.",
    vAddSlide: "+ Add slide (upload media)",
    vAddIntro: "+ Add intro scene",
    vAddOutro: "+ Add outro scene",
    vAutoLabel: "⚡ Auto-build a full video",
    vAutoHint: "Paste a news article URL (or its text). The AI reads the whole article and builds a complete video, using an infographic where there are numbers and clean text where there are none, plus an intro and outro.",
    vAutoUrl: "Article URL (optional)",
    vAutoTopic: "Topic or article text",
    vAutoBuildBtn: "Build the video",
    vAutoAiBtn: "✦ Build with AI",
    vIntroSceneLabel: "Intro scene settings",
    vIntroSceneHint: "Editing the selected intro scene — pick a background, write the two lines of text, and choose how the text animates in.",
    vIntroBgLabel: "Background",
    vIntroMainLabel: "Main text",
    vIntroSubInput2: "Secondary text",
    vIntroMotion2: "Text motion",
    vSlideHeadline: "Slide headline",
    vSlideDuration: "Slide duration (s)",
    vSlideFootage: "+ Add / replace footage on this slide",
    vSlideCaption: "Caption (top label)",
    vSlideSettingsNote: "These settings apply to the slide selected above. With no slides, they apply to your single video. Add a slide to give it its own separate settings.",
    vSlideSectionsLabel: "Scene settings",
    vTabFormat: "Format & export",
    vTabMotion: "Motion",
    vTabInfo: "Infographic",
    vInfoLabel: "Infographic builder",
    vInfoOnLabel: "Show infographic overlay",
    vInfoHint: "Type your title and stats below — the infographic builds itself as you write. No JSON needed.",
    vInfoAiLabel: "✦ Generate with AI",
    vInfoAiHint: "Describe your topic or paste a paragraph — AI turns it into a title and stats. First use opens a free Puter sign-in.",
    vInfoAiBtn: "Generate infographic",
    vInfoFormTitle: "Title",
    vInfoFormSubtitle: "Subtitle (optional)",
    vInfoFormSource: "Data source (recommended)",
    vInfoSourceNote: "Numbers shown are only as reliable as what you enter. Cite a real source so viewers can trust the data — AI-generated figures are estimates, not verified facts.",
    vInfoStatsHead: "Stats",
    vInfoAddRow: "+ Add a stat",
    vInfoAdvanced: "Advanced — edit raw JSON / import file",
    vInfoSyncBtn: "Load this JSON into the form",
    vInfoImportLabel: "Import JSON file",
    vInfoJsonLabel: "Infographic data (JSON)",
    vInfoStyleLabel: "Chart style",
    vInfoPosLabel: "Position",
    vInfoMotionLabel: "Entrance motion",
    vMotionLabel: "Motion & elements",
    vCamMotionLabel: "Camera motion",
    vTextAnimLabel: "Text animation",
    vOverlayLabel: "Overlay element",
    vMotionNote: "Every change updates the live preview instantly — no need to press Preview.",
    vTabText: "Text",
    vTabLogo: "Logo & cards",
    vTabNews: "News",
    vNewsLabel: "News banner",
    vNewsHint: "Add your own footage, then type the news details below — a broadcast-style banner is drawn over the video.",
    vNewsAiLabel: "✦ Summarize with AI",
    vNewsAiHint: "Paste an article or notes — AI writes a short kicker, headline and source. First use opens a free Puter sign-in.",
    vNewsAiBtn: "Summarize into banner",
    vNewsOnLabel: "Show news banner",
    vNewsKickerLabel: "Kicker / category",
    vNewsHeadlineLabel: "News headline",
    vNewsSourceLabel: "Source / reporter",
    vNewsStyleLabel: "Banner style",
    vNewsAccentLabel: "Banner accent",
    vNewsMotionLabel: "Entrance motion",
    vNewsClockLabel: "Show live clock",
    vTemplateLabel: "Template",
    vUploadLabel: "Media & music",
    vUploadHint: "Upload one video or image (mp4, webm, mov, jpg, png)",
    vQuickClipLabel: "Quick mode — single clip",
    vQuickClipHint: "Just one clip and no scenes? Upload a single video or image here instead of adding scenes.",
    vMusicLabel: "Background music",
    vMusicHint: "Optional: background music (mp3, wav) — applies to the whole video",
    vMediaModeNote: "Two ways to add footage: upload one clip here for a quick single-scene video, or use the Slides tab to build a multi-scene sequence. Music below applies to the whole video either way.",
    vLogoHint: "Optional: logo (transparent PNG recommended)",
    vFormatLabel: "Format & export",
    vAspectLabel: "Aspect ratio",
    vDurationLabel: "Duration (seconds)",
    vDurationNote: "Set any length you like. A shorter time simply trims the clip — it still plays at normal speed and ends early. A longer time slows the clip down so it stretches to fill the duration.",
    vFilterLabel: "Filter / grade",
    vSpeedLabel: "Playback speed",
    vTransitionLabel: "Transition in",
    vGrainLabel: "Film grain",
    vExportLabel: "Export settings",
    vExportSizeLabel: "Download size",
    vExportQualityLabel: "Download quality",
    vExportFormatLabel: "File format",
    vExportFormatNote: "MP4 is converted in your browser after recording. The first MP4 export downloads a one-time converter (~25 MB) and takes longer; later exports are quicker.",
    vExportInfo: "Higher size and quality look better but make a larger file.",
    vTextLabel: "Text layers",
    vHeadlineLabel: "Headline",
    vSubLabel: "Subtext",
    vCtaLabel: "Call to action",
    vTextPosLabel: "Text position",
    vTextSizeLabel: "Text size",
    vTextAutoNote: "Text sits on an automatic dark panel, so it stays readable on any photo or video.",
    vLogoLabel: "Logo & cards",
    vLogoPosLabel: "Logo position",
    vIntroLabel: "Intro — main text",
    vIntroSubLabel: "Intro — secondary text",
    vIntroMotionLabel: "Intro text motion",
    vOutroLabel: "Outro card text",
    vPreviewBtn: "Preview",
    vExportBtn: "Export video",
    vPreviewLabel: "Preview",
    vTimelineHint: "Drag the playhead to scrub",
    vTrackMedia: "Media",
    vTrackText: "Text",
    vTrackLogo: "Logo",
    vTrackMusic: "Music",
    vPreviewSizeLabel: "Preview size",
    vPlaceholder: "Choose a template and upload media to preview it here",
    navIntelligence: "Prompt lab",
    navJobs: "AI jobs",
    navAbout: "About",
    aboutEyebrow: "About",
    aboutTitle: "Built for the AI-curious",
    aboutText: "AI Radar is a free workspace to discover real AI tools, track live popularity, generate content, and build videos — all running in your browser.",
    aboutRole: "Creator & Designer",
    aboutCreditText: "Designed and built AI Radar — concept, interface, and the video studio.",
    aboutProjectRole: "Free static project",
    aboutProjectText: "Runs entirely client-side — three files, no server. Live data comes from the public GitHub API. No tracking, no accounts, no ads, ever.",
    changelogTitle: "Latest updates",
    cl21Title: "Cinematic design upgrade",
    cl21Text: "Premium animated backgrounds (aurora, ember, liquid mesh, spotlight and more), new infographic and text styles (progress pills, bold statement, split block, badge), template-driven title colours and fonts, and a Vox-style snappy motion across the studio.",
    cl20Title: "Smarter article-to-video",
    cl20Text: "Paste an article URL or text and the AI analyses the whole piece, choosing an infographic where there are numbers and clean text where there aren't. Plus per-slide footage and captions, professional news/text templates, working transitions on every slide, and a colour filter that grades the footage without washing out text.",
    cl19Title: "Auto video builder",
    cl19Text: "Describe a topic and the studio assembles a whole video for you — intro, infographic and news content slides, and an outro — in one click, with an optional AI scripting mode.",
    cl18Title: "Outro scenes & more designs",
    cl18Text: "Added outro scenes, 22 intro backgrounds, cinematic motion presets, clearer infographic text, per-slide element positions, and a graceful music fade-out.",
    cl17Title: "Intro scenes & richer motion",
    cl17Text: "New intro scene type in the Video Studio with 8 built-in backgrounds, dual animated text, and 12 motion presets. Scene-aware motion so every slide animates correctly.",
    cl16Title: "Full sidebar & cleaner UI",
    cl16Text: "Collapsible left sidebar navigation, redesigned chart and footer controls, a back-to-top button, and tighter mobile layouts throughout.",
    cl15Title: "MP4 export & real charts",
    cl15Text: "Video Studio now exports MP4. The infographic became a proper bar chart with a labelled axis, scale, and gridlines.",
    cl14Title: "Bigger tool catalogue",
    cl14Text: "Expanded to 45 curated AI tools, grouped into collapsible categories, with more live GitHub data coverage.",
    changelogNote: "AI Radar is actively maintained. This list shows the most recent notable changes.",
    aboutMissionTitle: "Why AI Radar exists",
    aboutMissionText: "The AI space moves faster than anyone can follow. AI Radar cuts through the noise — a calm, honest place to find genuinely useful tools, see what is actually gaining traction from live data, and create real work without paywalls, sign-ups, or tracking.",
    aboutStatTools: "curated AI tools",
    aboutStatFree: "free, no account",
    aboutStatLive: "GitHub data",
    aboutStatLiveValue: "Live",
    aboutStatPrivacy: "tracking or ads",
    aboutStatPrivacyValue: "Zero",
    aboutFeat1Title: "Tool finder",
    aboutFeat1Text: "Search and filter real AI tools by use case, price, and job — grouped and easy to scan.",
    aboutFeat2Title: "Live trend chart",
    aboutFeat2Text: "Popularity tracked from the public GitHub API, refreshed automatically — no guesswork.",
    aboutFeat3Title: "Video studio",
    aboutFeat3Text: "Build multi-scene videos with motion, infographics, and news banners — entirely in your browser.",
    aboutFeat4Title: "Caption & prompt tools",
    aboutFeat4Text: "Generate captions and refined prompts locally — fast, private, and free to use.",
    navRegister: "Register",
    startButton: "Start",
    heroEyebrow: "AI Radar — Live Intelligence",
    heroTitle: "Find. Compare. Create.",
    heroText:
      "Real AI tools, live popularity charts, Claude-powered captions and prompts, plus a professional video studio — one workspace, free in your browser.",
    heroPrimary: "Search tools",
    heroSecondary: "Generate captions",
    metricTools: "AI tools",
    metricFree: "Free plans",
    metricJobs: "Career paths",
    chipLive: "AA model index",
    toolsEyebrow: "Tool finder",
    toolsTitle: "Curated real AI tools",
    jumpToLabel: "Jump to tool",
    categoryLabel: "Category",
    budgetLabel: "Budget",
    sortLabel: "Sort",
    modelTypeLabel: "Model type",
    minScoreLabel: "Minimum score",
    compareEyebrow: "Compare",
    compareTitle: "Compare selected tools",
    clearCompare: "Clear",
    performanceEyebrow: "Live GitHub data",
    performanceTitle: "Live AI tools trend",
    liveLabel: "Live",
    refreshLabel: "Refresh",
    chartTabStars: "GitHub Stars",
    chartTabForks: "Forks",
    chartTabActivity: "Dev Activity",
    performanceText: "A live chart of real GitHub popularity for every AI tool in the finder. Data is fetched live from the public GitHub API and refreshes every 5 minutes. Tools you add to Compare are highlighted.",
    mediaEyebrow: "Media caption generator",
    mediaTitle: "Caption your photo or video for social media",
    mediaText: "Upload the photo or video you want to post, pick a platform, and get a ready-to-share caption with hooks and hashtags — built around your media.",
    mediaUploadLabel: "Upload image or video",
    mediaSubjectLabel: "What's in the photo/video? (required)",
    mediaGoalLabel: "Goal",
    platformLabel: "Platform",
    toneLabel: "Tone",
    generateCaption: "Generate caption",
    copyCaption: "Copy caption",
    copyJson: "Copy JSON",
    copyPrompt: "Copy prompt",
    mediaPlaceholder: "Upload media to preview it here",
    copied: "Copied.",
    studioEyebrow: "Free video template studio",
    studioTitle: "Create an animated video template from static uploads",
    studioText:
      "Upload images, set duration per slide, edit animated text elements, preview the timing, and export JSON or a real .webm video. It is free because it runs locally in the browser.",
    uploadLabel: "Upload static files",
    durationLabel: "Slide duration (seconds)",
    motionLabel: "Motion",
    addSlide: "Add slide",
    exportTemplate: "Export template JSON",
    exportVideo: "Export video (.webm)",
    slideTitleLabel: "Slide title",
    slideCaptionLabel: "Slide caption",
    chartDataLabel: "Chart values",
    previewPlaceholder: "Upload an image to preview your template",
    jobsEyebrow: "AI career helper",
    jobsTitle: "Find a practical AI work direction",
    jobBoardTitle: "Live job source board",
    skillsLabel: "Your skills",
    jobTitleLabel: "Target role",
    jobLocationLabel: "Location",
    skillsButton: "Suggest path",
    intelEyebrow: "AI utilities",
    intelTitle: "Generate clean prompts and JSON",
    promptDescLabel: "Describe what you want to create",
    promptStyleLabel: "Style",
    promptGenBtn: "Generate prompt",
    promptNote: "Generates a single ready-to-paste prompt in the chosen style — just the prompt, nothing else.",
    jsonDescLabel: "Describe any data, product, or idea",
    jsonGenBtn: "Generate JSON",
    jsonNote: "Outputs only clean, valid JSON — no explanation, no extra text.",
    simplePromptLabel: "Simple prompt",
    enhancePrompt: "Enhance prompt",
    textJsonLabel: "Text to JSON",
    convertJson: "Convert to JSON",
    registerEyebrow: "Account",
    registerTitle: "Create a local test account",
    registerText: "This demo stores registration data in your browser only. A real launch needs authentication on a backend.",
    nameLabel: "Name",
    emailLabel: "Email",
    roleLabel: "Main goal",
    registerButton: "Register",
    registered: "Registration saved locally.",
    allCategories: "All categories",
    allBudgets: "All budgets",
    freeBudget: "Free or freemium",
    under20: "Under $20",
    proBudget: "Pro tools",
    sortScore: "Best match",
    sortPrice: "Lowest price",
    sortName: "Name",
    noTools: "No tools found. Try a broader search.",
    addCompare: "Add to compare",
    removeCompare: "Remove",
    officialLink: "Official link",
    pricing: "Pricing",
    emptyCompare: "Add tools from the cards to compare them here.",
    tableTool: "Tool",
    tableCategory: "Category",
    tablePrice: "Price",
    tableUse: "Best use",
    tableJobs: "Related jobs",
    tableLink: "Link",
    open: "Open",
    recommendedTools: "Recommended tools",
    sourceHint: "Opens a real public search in a new tab",
    templateEmpty: "Add at least one uploaded slide first.",
    downloaded: "Template JSON downloaded.",
    videoExporting: "Rendering video... keep this tab open.",
    videoReady: "Video downloaded.",
    videoUnsupported: "Your browser does not support video export here.",
    noFile: "Upload images first.",
    deleteSlide: "Delete"
  },
  fa: {
    navGroupExplore: "کاوش",
    navGroupCreate: "ساخت",
    navTools: "ابزارها",
    themeLight: "روشن",
    themeDark: "تیره",
    navPerformance: "چارت زنده",
    navMedia: "\u06a9\u067e\u0634\u0646 AI",
    navStudio: "استودیوی ویدیو",
    studioEyebrow: "استودیوی پیشرفته ویدیو",
    studioTitle: "یک ویدیوی کامل و لوکس بساز",
    studioText: "تب‌ها را به ترتیب بزن: ۱) قالب، ۲) رسانه، ۳) فرمت، ۴) متن، ۵) لوگو. خط زمان زیر پیش‌نمایش لایه‌ها را نشان می‌دهد — نشانگر قرمز را بکش. پیش‌نمایش برای پخش، خروجی برای ذخیره ویدیو.",
    vTabTemplate: "قالب",
    vTabMedia: "رسانه",
    vTabSlides: "اسلایدها",
    vSlidesLabel: "دنباله اسلاید",
    vSlidesHint: "چند اسلاید اضافه کن — هرکدام با رسانه، عنوان و مدت خودش. پشت سر هم به‌صورت یک ویدیو پخش می‌شوند.",
    vAddSlide: "+ افزودن اسلاید (آپلود رسانه)",
    vAddIntro: "+ افزودن صحنه اینترو",
    vAddOutro: "+ افزودن صحنه پایانی",
    vAutoLabel: "⚡ ساخت خودکار ویدیوی کامل",
    vAutoHint: "لینک یک مقاله خبری (یا متن آن) را بچسبان. هوش مصنوعی کل مقاله را می‌خواند و یک ویدیوی کامل می‌سازد — هرجا عدد باشد اینفوگرافیک و هرجا نباشد متن — به‌همراه اینترو و اوترو.",
    vAutoUrl: "لینک مقاله (اختیاری)",
    vAutoTopic: "موضوع یا متن مقاله",
    vAutoBuildBtn: "ساخت ویدیو",
    vAutoAiBtn: "✦ ساخت با هوش مصنوعی",
    vIntroSceneLabel: "تنظیمات صحنه اینترو",
    vIntroSceneHint: "در حال ویرایش صحنه اینتروی انتخاب‌شده — یک پس‌زمینه انتخاب کن، دو خط متن بنویس و حرکت ورود متن را انتخاب کن.",
    vIntroBgLabel: "پس‌زمینه",
    vIntroMainLabel: "متن اصلی",
    vIntroSubInput2: "متن فرعی",
    vIntroMotion2: "حرکت متن",
    vSlideHeadline: "عنوان اسلاید",
    vSlideDuration: "مدت اسلاید (ثانیه)",
    vSlideFootage: "+ افزودن / جایگزینی فوتیج این صحنه",
    vSlideCaption: "کپشن (برچسب بالا)",
    vSlideSettingsNote: "این تنظیمات روی اسلاید انتخاب‌شده اعمال می‌شود. بدون اسلاید، روی ویدیوی تکی شما اعمال می‌شود. برای تنظیمات جداگانه، اسلاید اضافه کن.",
    vSlideSectionsLabel: "تنظیمات صحنه",
    vTabFormat: "فرمت و خروجی",
    vTabMotion: "موشن",
    vTabInfo: "اینفوگرافیک",
    vInfoLabel: "سازنده اینفوگرافیک",
    vInfoOnLabel: "نمایش اینفوگرافیک",
    vInfoHint: "عنوان و آمارها را پایین بنویس — اینفوگرافیک همزمان با نوشتن ساخته می‌شود. نیازی به JSON نیست.",
    vInfoAiLabel: "✦ ساخت با هوش مصنوعی",
    vInfoAiHint: "موضوعت را توصیف کن یا یک پاراگراف بچسبان — هوش مصنوعی آن را به عنوان و آمار تبدیل می‌کند. اولین استفاده یک ورود رایگان Puter باز می‌کند.",
    vInfoAiBtn: "ساخت اینفوگرافیک",
    vInfoFormTitle: "عنوان",
    vInfoFormSubtitle: "زیرعنوان (اختیاری)",
    vInfoFormSource: "منبع داده (توصیه‌شده)",
    vInfoSourceNote: "اعداد نمایش‌داده‌شده فقط به اندازه چیزی که وارد می‌کنی معتبرند. یک منبع واقعی ذکر کن تا بینندگان به داده‌ها اعتماد کنند — اعداد تولیدشده با هوش مصنوعی تخمین هستند، نه حقایق تأییدشده.",
    vInfoStatsHead: "آمارها",
    vInfoAddRow: "+ افزودن آمار",
    vInfoAdvanced: "پیشرفته — ویرایش JSON خام / وارد کردن فایل",
    vInfoSyncBtn: "بارگذاری این JSON در فرم",
    vInfoImportLabel: "وارد کردن فایل JSON",
    vInfoJsonLabel: "داده اینفوگرافیک (JSON)",
    vInfoStyleLabel: "سبک نمودار",
    vInfoPosLabel: "موقعیت",
    vInfoMotionLabel: "حرکت ورود",
    vMotionLabel: "موشن و المان‌ها",
    vCamMotionLabel: "حرکت دوربین",
    vTextAnimLabel: "انیمیشن متن",
    vOverlayLabel: "المان رویی",
    vMotionNote: "هر تغییری فوراً پیش‌نمایش زنده را به‌روز می‌کند — نیازی به زدن پیش‌نمایش نیست.",
    vTabText: "متن",
    vTabLogo: "لوگو و کارت",
    vTabNews: "اخبار",
    vNewsLabel: "بنر خبری",
    vNewsHint: "ابتدا فیلم خودت را اضافه کن، سپس جزئیات خبر را پایین بنویس — یک بنر شبیه پخش تلویزیونی روی ویدیو کشیده می‌شود.",
    vNewsAiLabel: "✦ خلاصه با هوش مصنوعی",
    vNewsAiHint: "یک مقاله یا یادداشت بچسبان — هوش مصنوعی یک تیتر کوتاه، سرتیتر و منبع می‌نویسد. اولین استفاده یک ورود رایگان Puter باز می‌کند.",
    vNewsAiBtn: "خلاصه در بنر",
    vNewsOnLabel: "نمایش بنر خبری",
    vNewsKickerLabel: "تیتر کوتاه / دسته",
    vNewsHeadlineLabel: "تیتر خبر",
    vNewsSourceLabel: "منبع / خبرنگار",
    vNewsStyleLabel: "سبک بنر",
    vNewsAccentLabel: "رنگ بنر",
    vNewsMotionLabel: "حرکت ورود",
    vNewsClockLabel: "نمایش ساعت زنده",
    vTemplateLabel: "قالب",
    vUploadLabel: "رسانه و موسیقی",
    vUploadHint: "یک ویدیو یا تصویر آپلود کن (mp4, webm, mov, jpg, png)",
    vQuickClipLabel: "حالت سریع — تک‌کلیپ",
    vQuickClipHint: "فقط یک کلیپ و بدون صحنه؟ به‌جای افزودن صحنه، یک ویدیو یا تصویر اینجا آپلود کن.",
    vMusicLabel: "موسیقی پس‌زمینه",
    vMusicHint: "اختیاری: موسیقی پس‌زمینه (mp3, wav) — روی کل ویدیو اعمال می‌شود",
    vMediaModeNote: "دو راه برای افزودن فیلم: یک کلیپ اینجا آپلود کن برای ویدیوی تک‌صحنه، یا از تب اسلایدها برای ساخت دنباله چندصحنه‌ای استفاده کن. موسیقی زیر روی کل ویدیو اعمال می‌شود.",
    vLogoHint: "اختیاری: لوگو (png شفاف توصیه می‌شود)",
    vFormatLabel: "فرمت و خروجی",
    vAspectLabel: "نسبت تصویر",
    vDurationLabel: "مدت (ثانیه)",
    vDurationNote: "هر طولی بخواهی تنظیم کن. کلیپ کش می‌آید تا آن را پر کند — بلندتر از کلیپ یعنی پخش آهسته، کوتاه‌تر یعنی سریع‌تر. همیشه یک‌بار از ابتدا تا انتها اجرا می‌شود، بدون توقف یا تکرار.",
    vFilterLabel: "فیلتر / گرید",
    vSpeedLabel: "سرعت پخش",
    vTransitionLabel: "ترانزیشن ورودی",
    vGrainLabel: "دانه‌دانه فیلم",
    vExportLabel: "تنظیمات خروجی",
    vExportSizeLabel: "اندازه دانلود",
    vExportQualityLabel: "کیفیت دانلود",
    vExportFormatLabel: "قالب فایل",
    vExportFormatNote: "MP4 پس از ضبط، داخل مرورگر تبدیل می‌شود. اولین خروجی MP4 یک مبدل یک‌بارمصرف (~۲۵ مگابایت) دانلود می‌کند و بیشتر طول می‌کشد؛ خروجی‌های بعدی سریع‌ترند.",
    vExportInfo: "اندازه و کیفیت بالاتر بهتر دیده می‌شود اما فایل بزرگ‌تری می‌سازد.",
    vTextLabel: "لایه‌های متن",
    vHeadlineLabel: "تیتر",
    vSubLabel: "زیرنویس",
    vCtaLabel: "دعوت به اقدام",
    vTextPosLabel: "موقعیت متن",
    vTextSizeLabel: "اندازه متن",
    vTextAutoNote: "متن روی یک پنل تیره خودکار قرار می‌گیرد تا روی هر عکس یا ویدیویی خوانا بماند.",
    vLogoLabel: "۵ · لوگو و کارت‌ها",
    vLogoPosLabel: "موقعیت لوگو",
    vIntroLabel: "اینترو — متن اصلی",
    vIntroSubLabel: "اینترو — متن فرعی",
    vIntroMotionLabel: "حرکت متن اینترو",
    vOutroLabel: "متن کارت اوترو",
    vPreviewBtn: "پیش‌نمایش",
    vExportBtn: "خروجی ویدیو",
    vPreviewLabel: "پیش‌نمایش",
    vTimelineHint: "برای جابه‌جایی، نشانگر را بکش",
    vTrackMedia: "رسانه",
    vTrackText: "متن",
    vTrackLogo: "لوگو",
    vTrackMusic: "موسیقی",
    vPreviewSizeLabel: "اندازه پیش‌نمایش",
    vPlaceholder: "یک قالب انتخاب کن و رسانه آپلود کن تا اینجا پیش‌نمایش داده شود",
    navIntelligence: "لابراتوار پرامپت",
    navJobs: "کار AI",
    navAbout: "درباره",
    aboutEyebrow: "درباره",
    aboutTitle: "ساخته‌شده برای علاقه‌مندان AI",
    aboutText: "AI Radar یک فضای کاری رایگان برای کشف ابزارهای واقعی AI، دنبال‌کردن محبوبیت زنده، تولید محتوا و ساخت ویدیو — همه داخل مرورگر شما.",
    aboutRole: "سازنده و طراح",
    aboutCreditText: "طراحی و ساخت AI Radar — ایده، رابط کاربری و استودیوی ویدیو.",
    aboutProjectRole: "پروژه استاتیک رایگان",
    aboutProjectText: "کاملاً سمت کلاینت اجرا می‌شود — سه فایل، بدون سرور. داده زنده از API عمومی گیت‌هاب. بدون ردیابی، بدون حساب، بدون تبلیغ.",
    changelogTitle: "آخرین به‌روزرسانی‌ها",
    cl21Title: "ارتقای طراحی سینمایی",
    cl21Text: "پس‌زمینه‌های متحرک پریمیوم (شفق، اخگر، مش مایع، نورافکن و بیشتر)، سبک‌های جدید اینفوگرافیک و متن (پیل پیشرفت، جمله درشت، بلوک تقسیم، نشان)، رنگ و فونت عنوان بر اساس قالب، و حرکت سریع سبک Vox در کل استودیو.",
    cl20Title: "تبدیل هوشمندتر مقاله به ویدیو",
    cl20Text: "لینک یا متن مقاله را بچسبان تا هوش مصنوعی کل مطلب را تحلیل کند و هرجا عدد باشد اینفوگرافیک و هرجا نباشد متن بسازد. به‌علاوه فوتیج و کپشن برای هر اسلاید، قالب‌های حرفه‌ای خبری/متنی، ترنزیشن روی همه اسلایدها و فیلتر رنگی که فوتیج را رنگ‌آمیزی می‌کند بدون محو شدن متن.",
    cl19Title: "سازنده خودکار ویدیو",
    cl19Text: "یک موضوع را توصیف کن و استودیو یک ویدیوی کامل برایت می‌سازد — اینترو، اسلایدهای اینفوگرافیک و خبری، و اوترو — با یک کلیک و حالت اختیاری نگارش با هوش مصنوعی.",
    cl18Title: "صحنه‌های پایانی و طرح‌های بیشتر",
    cl18Text: "افزودن صحنه‌های اوترو، ۲۲ پس‌زمینه اینترو، پیش‌تنظیم‌های حرکت سینمایی، متن واضح‌تر اینفوگرافیک، موقعیت عناصر برای هر اسلاید و محو تدریجی موسیقی.",
    cl17Title: "صحنه‌های اینترو و حرکت غنی‌تر",
    cl17Text: "نوع صحنه اینتروی جدید در استودیو ویدیو با ۸ پس‌زمینه آماده، متن دوگانه متحرک و ۱۲ پیش‌تنظیم حرکت. حرکت مبتنی بر صحنه تا هر اسلاید درست انیمیت شود.",
    cl16Title: "نوار کناری کامل و رابط تمیزتر",
    cl16Text: "ناوبری نوار کناری چپ تاشو، کنترل‌های بازطراحی‌شده نمودار و فوتر، دکمه بازگشت به بالا و چیدمان موبایل بهتر.",
    cl15Title: "خروجی MP4 و نمودار واقعی",
    cl15Text: "استودیو ویدیو حالا MP4 خروجی می‌دهد. اینفوگرافیک به یک نمودار میله‌ای واقعی با محور، مقیاس و خطوط شبکه تبدیل شد.",
    cl14Title: "کاتالوگ بزرگ‌تر ابزارها",
    cl14Text: "گسترش به ۴۵ ابزار هوش مصنوعی منتخب، دسته‌بندی‌شده در گروه‌های تاشو، با پوشش بیشتر داده زنده گیت‌هاب.",
    changelogNote: "AI Radar فعالانه نگهداری می‌شود. این فهرست مهم‌ترین تغییرات اخیر را نشان می‌دهد.",
    aboutMissionTitle: "چرا AI Radar وجود دارد",
    aboutMissionText: "دنیای هوش مصنوعی سریع‌تر از آنی پیش می‌رود که کسی بتواند دنبال کند. AI Radar از میان شلوغی عبور می‌کند — جایی آرام و صادقانه برای یافتن ابزارهای واقعاً مفید، دیدن آنچه با داده زنده در حال رشد است، و ساختن کار واقعی بدون دیوار پرداخت، ثبت‌نام یا ردیابی.",
    aboutStatTools: "ابزار هوش مصنوعی منتخب",
    aboutStatFree: "رایگان، بدون حساب",
    aboutStatLive: "داده گیت‌هاب",
    aboutStatLiveValue: "زنده",
    aboutStatPrivacy: "ردیابی یا تبلیغ",
    aboutStatPrivacyValue: "صفر",
    aboutFeat1Title: "یابنده ابزار",
    aboutFeat1Text: "ابزارهای واقعی هوش مصنوعی را بر اساس کاربرد، قیمت و شغل جستجو و فیلتر کن — دسته‌بندی‌شده و خوانا.",
    aboutFeat2Title: "نمودار روند زنده",
    aboutFeat2Text: "محبوبیت از API عمومی گیت‌هاب دنبال می‌شود و خودکار به‌روز می‌شود — بدون حدس.",
    aboutFeat3Title: "استودیو ویدیو",
    aboutFeat3Text: "ویدیوهای چندصحنه‌ای با موشن، اینفوگرافیک و بنر خبری بساز — کاملاً در مرورگر.",
    aboutFeat4Title: "ابزار کپشن و پرامپت",
    aboutFeat4Text: "کپشن و پرامپت دقیق را به‌صورت محلی بساز — سریع، خصوصی و رایگان.",
    navRegister: "رجیستر",
    startButton: "شروع",
    heroEyebrow: "AI Radar — هوش زنده",
    heroTitle: "پیدا کن. مقایسه کن. بساز.",
    heroText:
      "ابزارهای واقعی AI، نمودار محبوبیت زنده، کپشن و پرامپت با قدرت Claude، و یک استودیوی حرفه‌ای ویدیو — همه در یک فضا، رایگان داخل مرورگر.",
    heroPrimary: "جست‌وجوی ابزار",
    heroSecondary: "ساخت کپشن",
    metricTools: "ابزار واقعی",
    metricFree: "پلن رایگان",
    metricJobs: "مسیر شغلی",
    chipLive: "شاخص مدل AA",
    toolsEyebrow: "Tool finder",
    toolsTitle: "ابزارهای واقعی انتخاب‌شده",
    jumpToLabel: "پرش به ابزار",
    categoryLabel: "دسته",
    budgetLabel: "بودجه",
    sortLabel: "مرتب‌سازی",
    modelTypeLabel: "نوع مدل",
    minScoreLabel: "حداقل امتیاز",
    compareEyebrow: "مقایسه",
    compareTitle: "مقایسه ابزارهای انتخاب‌شده",
    clearCompare: "پاک کردن",
    performanceEyebrow: "داده زنده گیت‌هاب",
    performanceTitle: "ترند زنده ابزارهای AI",
    liveLabel: "زنده",
    refreshLabel: "تازه‌سازی",
    chartTabStars: "ستاره‌های گیت‌هاب",
    chartTabForks: "فورک‌ها",
    chartTabActivity: "فعالیت توسعه",
    performanceText: "نمودار زنده از محبوبیت واقعی هر ابزار AI در گیت‌هاب. داده به‌صورت زنده از API عمومی گیت‌هاب گرفته می‌شود و هر ۵ دقیقه به‌روز می‌شود. ابزارهایی که به بخش مقایسه اضافه می‌کنی هایلایت می‌شوند.",
    mediaEyebrow: "تولید کپشن رسانه",
    mediaTitle: "برای عکس یا ویدیوی خود کپشن شبکه اجتماعی بساز",
    mediaText: "مدیا را آپلود کن، هدف را بنویس، پلتفرم را انتخاب کن و کپشن، hook، هشتگ ترند و JSON متادیتا را محلی تولید کن.",
    mediaUploadLabel: "آپلود عکس یا ویدیو",
    mediaSubjectLabel: "در عکس/ویدیو چه چیزی هست؟ (الزامی)",
    mediaGoalLabel: "هدف",
    platformLabel: "پلتفرم",
    toneLabel: "لحن",
    generateCaption: "تولید کپشن",
    copyCaption: "کپی کپشن",
    copyJson: "کپی JSON",
    copyPrompt: "کپی پرامپت",
    mediaPlaceholder: "مدیا را آپلود کن تا اینجا نمایش داده شود",
    copied: "کپی شد.",
    studioEyebrow: "استودیو رایگان تمپلیت ویدیو",
    studioTitle: "از فایل‌های استاتیک، تمپلیت ویدیویی متحرک بساز",
    studioText:
      "تصویرها را آپلود کن، برای هر اسلاید زمان بگذار، متن‌های متحرک را ویرایش کن، پیش‌نمایش بگیر و خروجی JSON یا ویدیوی واقعی .webm بگیر. چون داخل مرورگر اجرا می‌شود رایگان است.",
    uploadLabel: "آپلود فایل‌های استاتیک",
    durationLabel: "زمان هر اسلاید (ثانیه)",
    motionLabel: "موشن",
    addSlide: "افزودن اسلاید",
    exportTemplate: "خروجی JSON تمپلیت",
    exportVideo: "خروجی ویدیو (.webm)",
    slideTitleLabel: "عنوان اسلاید",
    slideCaptionLabel: "کپشن اسلاید",
    chartDataLabel: "مقادیر نمودار",
    previewPlaceholder: "برای پیش‌نمایش، یک تصویر آپلود کن",
    jobsEyebrow: "راهنمای کار AI",
    jobsTitle: "یک مسیر کاری عملی در AI پیدا کن",
    jobBoardTitle: "برد منابع شغلی زنده",
    skillsLabel: "مهارت‌های تو",
    jobTitleLabel: "عنوان شغل هدف",
    jobLocationLabel: "لوکیشن",
    skillsButton: "پیشنهاد مسیر",
    intelEyebrow: "ابزارهای AI",
    intelTitle: "تولید پرامپت و JSON تمیز",
    promptDescLabel: "آنچه می‌خواهی بسازی را توصیف کن",
    promptStyleLabel: "سبک",
    promptGenBtn: "تولید پرامپت",
    promptNote: "یک پرامپت آماده در سبک انتخاب‌شده تولید می‌کند — فقط پرامپت، بدون چیز اضافه.",
    jsonDescLabel: "هر داده، محصول یا ایده را توصیف کن",
    jsonGenBtn: "تولید JSON",
    jsonNote: "فقط JSON تمیز و معتبر خروجی می‌دهد — بدون توضیح و متن اضافه.",
    simplePromptLabel: "پرامپت ساده",
    enhancePrompt: "تبدیل به پرامپت پیشرفته",
    textJsonLabel: "متن به JSON",
    convertJson: "تبدیل به JSON",
    registerEyebrow: "اکانت",
    registerTitle: "ساخت اکانت تست محلی",
    registerText: "این دمو اطلاعات رجیستر را فقط داخل مرورگر ذخیره می‌کند. نسخه واقعی نیاز به احراز هویت بک‌اند دارد.",
    nameLabel: "نام",
    emailLabel: "ایمیل",
    roleLabel: "هدف اصلی",
    registerButton: "رجیستر",
    registered: "رجیستر به صورت محلی ذخیره شد.",
    allCategories: "همه دسته‌ها",
    allBudgets: "همه بودجه‌ها",
    freeBudget: "رایگان یا فریمیوم",
    under20: "زیر ۲۰ دلار",
    proBudget: "ابزارهای حرفه‌ای",
    sortScore: "بهترین پیشنهاد",
    sortPrice: "ارزان‌تر",
    sortName: "نام",
    noTools: "ابزاری پیدا نشد. جست‌وجو را کلی‌تر کن.",
    addCompare: "افزودن به مقایسه",
    removeCompare: "حذف",
    officialLink: "لینک رسمی",
    pricing: "قیمت",
    emptyCompare: "از کارت ابزارها چند گزینه را به مقایسه اضافه کن.",
    tableTool: "ابزار",
    tableCategory: "دسته",
    tablePrice: "قیمت",
    tableUse: "بهترین کاربرد",
    tableJobs: "کارهای مرتبط",
    tableLink: "لینک",
    open: "باز کردن",
    recommendedTools: "ابزار پیشنهادی",
    sourceHint: "جست‌وجوی واقعی را در تب جدید باز می‌کند",
    templateEmpty: "اول حداقل یک اسلاید آپلود شده اضافه کن.",
    downloaded: "فایل JSON تمپلیت دانلود شد.",
    videoExporting: "در حال ساخت ویدیو... این تب را باز نگه دار.",
    videoReady: "ویدیو دانلود شد.",
    videoUnsupported: "مرورگر اینجا از خروجی ویدیو پشتیبانی نمی‌کند.",
    noFile: "اول تصویر آپلود کن.",
    deleteSlide: "حذف"
  }
};

const tools = [
  {
    name: "ChatGPT",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: {
      en: "Writing, coding, data analysis, brainstorming, file work, and everyday AI assistance.",
      fa: "نوشتن، کدنویسی، تحلیل داده، ایده‌پردازی، کار با فایل و دستیار عمومی روزمره."
    },
    price: 20,
    pricing: { en: "Free plan + Plus from about $20/mo", fa: "پلن رایگان + Plus حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 98,
    jobs: ["Prompt Engineer", "AI Content Specialist", "Automation Builder"],
    url: "https://chatgpt.com",
    tags: ["writing", "coding", "analysis"]
  },
  {
    name: "Claude",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: {
      en: "Long-context writing, reasoning, research synthesis, planning, and document work.",
      fa: "تحلیل متن طولانی، نوشتن، استدلال، خلاصه‌سازی تحقیق، برنامه‌ریزی و کار با سند."
    },
    price: 20,
    pricing: { en: "Free plan + Pro from about $20/mo", fa: "پلن رایگان + Pro حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 95,
    jobs: ["Research Assistant", "AI Writer", "Operations Analyst"],
    url: "https://claude.ai",
    tags: ["research", "writing", "documents"]
  },
  {
    name: "Perplexity",
    category: { en: "Research", fa: "تحقیق و سرچ" },
    useCase: {
      en: "Web research with citations, quick comparisons, source discovery, and market scanning.",
      fa: "جست‌وجوی وب با منبع، مقایسه سریع، کشف منابع و بررسی بازار."
    },
    price: 20,
    pricing: { en: "Free plan + Pro from about $20/mo", fa: "پلن رایگان + Pro حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 92,
    jobs: ["Market Researcher", "AI Research Assistant"],
    url: "https://www.perplexity.ai",
    tags: ["search", "sources", "research"]
  },
  {
    name: "Cursor",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: {
      en: "AI-native code editor for building, refactoring, understanding, and shipping software.",
      fa: "ویرایشگر کد AI برای ساخت، اصلاح، فهمیدن و انتشار نرم‌افزار."
    },
    price: 20,
    pricing: { en: "Free tier + Pro from about $20/mo", fa: "نسخه رایگان محدود + Pro حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 91,
    jobs: ["AI Developer", "Frontend Developer", "Product Engineer"],
    url: "https://www.cursor.com",
    tags: ["coding", "IDE", "developer"]
  },
  {
    name: "GitHub Copilot",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: {
      en: "Code completion, chat, pull request assistance, test generation, and developer workflow support.",
      fa: "تکمیل کد، چت کدنویسی، کمک در pull request، تولید تست و پشتیبانی جریان کاری توسعه."
    },
    price: 10,
    pricing: { en: "Individual plan from about $10/mo", fa: "پلن فردی حدود ۱۰ دلار ماهانه" },
    plan: "paid",
    score: 88,
    jobs: ["Software Developer", "QA Automation"],
    url: "https://github.com/features/copilot",
    tags: ["github", "code", "testing"]
  },
  {
    name: "Canva AI",
    category: { en: "Design", fa: "طراحی" },
    useCase: {
      en: "Social posts, presentations, brand assets, image generation, and fast visual production.",
      fa: "پست شبکه اجتماعی، ارائه، asset برند، تولید تصویر و ساخت سریع محتوای بصری."
    },
    price: 15,
    pricing: { en: "Free tier + Pro pricing varies by region", fa: "نسخه رایگان + Pro بسته به منطقه متفاوت است" },
    plan: "freemium",
    score: 86,
    jobs: ["AI Designer", "Social Media Creator"],
    url: "https://www.canva.com/ai",
    tags: ["design", "slides", "social"]
  },
  {
    name: "Runway",
    category: { en: "Video", fa: "ویدیو" },
    useCase: {
      en: "AI video generation, editing, creative effects, short ads, and visual storytelling.",
      fa: "تولید و ویرایش ویدیو، افکت خلاقانه، تبلیغات کوتاه و روایت بصری."
    },
    price: 15,
    pricing: { en: "Free credits + paid plans", fa: "اعتبار رایگان محدود + پلن‌های پولی" },
    plan: "freemium",
    score: 85,
    jobs: ["AI Video Creator", "Motion Designer"],
    url: "https://runwayml.com",
    tags: ["video", "motion", "ads"]
  },
  {
    name: "ElevenLabs",
    category: { en: "Audio", fa: "صدا" },
    useCase: {
      en: "Voice generation, dubbing, narration, podcasts, and multilingual audio production.",
      fa: "تولید صدا، دوبله، روایت، پادکست و ساخت صوت چندزبانه."
    },
    price: 5,
    pricing: { en: "Free tier + starter from about $5/mo", fa: "نسخه رایگان + شروع از حدود ۵ دلار ماهانه" },
    plan: "freemium",
    score: 84,
    jobs: ["AI Voice Producer", "Podcast Editor"],
    url: "https://elevenlabs.io",
    tags: ["voice", "audio", "dubbing"]
  },
  {
    name: "Hugging Face",
    category: { en: "Models and datasets", fa: "مدل و دیتاست" },
    useCase: {
      en: "Open models, datasets, spaces, demos, and infrastructure for ML and AI prototypes.",
      fa: "مدل متن‌باز، دیتاست، دمو، spaces و زیرساخت برای نمونه‌سازی ML و AI."
    },
    price: 0,
    pricing: { en: "Free community platform + paid compute options", fa: "پلتفرم رایگان جامعه + گزینه‌های پردازشی پولی" },
    plan: "free",
    score: 90,
    jobs: ["ML Engineer", "AI App Prototyper"],
    url: "https://huggingface.co",
    tags: ["open source", "models", "datasets"]
  },
  {
    name: "Gamma",
    category: { en: "Presentations", fa: "ارائه" },
    useCase: {
      en: "AI presentations, pitch decks, docs, microsites, and fast visual storytelling.",
      fa: "ساخت ارائه AI، pitch deck، سند، میکروسایت و روایت بصری سریع."
    },
    price: 10,
    pricing: { en: "Free tier + paid plans from about $10/mo", fa: "نسخه رایگان + پلن‌های پولی از حدود ۱۰ دلار ماهانه" },
    plan: "freemium",
    score: 82,
    jobs: ["Presentation Designer", "Startup Operator"],
    url: "https://gamma.app",
    tags: ["slides", "pitch", "docs"]
  },
  {
    name: "Zapier AI",
    category: { en: "Automation", fa: "اتوماسیون" },
    useCase: {
      en: "Automate work across apps, connect forms, CRMs, email, spreadsheets, and AI actions.",
      fa: "اتوماسیون بین ابزارها، اتصال فرم، CRM، ایمیل، spreadsheet و اکشن‌های AI."
    },
    price: 20,
    pricing: { en: "Free tier + paid plans", fa: "نسخه رایگان محدود + پلن‌های پولی" },
    plan: "freemium",
    score: 83,
    jobs: ["Automation Specialist", "AI Workflow Builder"],
    url: "https://zapier.com/ai",
    tags: ["automation", "no-code", "business"]
  },
  {
    name: "Notion AI",
    category: { en: "Productivity", fa: "بهره‌وری" },
    useCase: {
      en: "Summaries, writing, knowledge management, docs, meeting notes, and project planning.",
      fa: "خلاصه‌سازی، نوشتن، مدیریت دانش، مستندات، یادداشت جلسه و برنامه‌ریزی پروژه."
    },
    price: 10,
    pricing: { en: "Paid add-on for Notion plans", fa: "افزونه پولی روی پلن‌های Notion" },
    plan: "paid",
    score: 80,
    jobs: ["Operations Assistant", "Knowledge Manager"],
    url: "https://www.notion.com/product/ai",
    tags: ["notes", "docs", "teams"]
  }
];

tools.push(
  {
    name: "Gemini",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Google AI assistant for search, writing, coding, images, and Workspace workflows.", fa: "دستیار AI گوگل برای سرچ، نوشتن، کدنویسی، تصویر و جریان کاری Workspace." },
    price: 20,
    pricing: { en: "Free access + Google AI Pro paid plan", fa: "دسترسی رایگان + پلن پولی Google AI Pro" },
    plan: "freemium",
    score: 94,
    jobs: ["AI Researcher", "Productivity Specialist"],
    url: "https://gemini.google.com",
    tags: ["google", "search", "workspace"],
    modelType: "multimodal",
    logo: "G"
  },
  {
    name: "Midjourney",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "High-quality image generation for creative campaigns, concepts, ads, and moodboards.", fa: "تولید تصویر باکیفیت برای کمپین، کانسپت، تبلیغ و moodboard." },
    price: 10,
    pricing: { en: "Paid plans from about $10/mo", fa: "پلن پولی از حدود ۱۰ دلار ماهانه" },
    plan: "paid",
    score: 89,
    jobs: ["AI Image Artist", "Creative Director"],
    url: "https://www.midjourney.com",
    tags: ["image", "art", "creative"],
    modelType: "image",
    logo: "MJ"
  },
  {
    name: "Adobe Firefly",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "Commercial-friendly generative image tools inside Adobe creative workflows.", fa: "ابزار تولید تصویر مناسب کار تجاری داخل جریان کاری Adobe." },
    price: 5,
    pricing: { en: "Free credits + paid Adobe plans", fa: "اعتبار رایگان + پلن‌های Adobe" },
    plan: "freemium",
    score: 84,
    jobs: ["Graphic Designer", "Brand Designer"],
    url: "https://firefly.adobe.com",
    tags: ["image", "design", "adobe"],
    modelType: "image",
    logo: "AF"
  },
  {
    name: "Suno",
    category: { en: "Audio", fa: "صدا" },
    useCase: { en: "Generate songs, music concepts, jingles, and audio ideas from text prompts.", fa: "تولید آهنگ، ایده موسیقی، jingle و صوت از متن." },
    price: 10,
    pricing: { en: "Free credits + paid plans", fa: "اعتبار رایگان + پلن‌های پولی" },
    plan: "freemium",
    score: 82,
    jobs: ["AI Music Creator", "Content Producer"],
    url: "https://suno.com",
    tags: ["music", "audio", "song"],
    modelType: "audio",
    logo: "SU"
  },
  {
    name: "Mistral Le Chat",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Fast European AI assistant and API ecosystem for business and developer workflows.", fa: "دستیار و اکوسیستم API سریع اروپایی برای کسب‌وکار و توسعه‌دهنده‌ها." },
    price: 15,
    pricing: { en: "Free access + paid API and pro options", fa: "دسترسی رایگان + API و گزینه‌های حرفه‌ای پولی" },
    plan: "freemium",
    score: 86,
    jobs: ["AI Developer", "Enterprise AI Consultant"],
    url: "https://chat.mistral.ai",
    tags: ["llm", "api", "enterprise"],
    modelType: "text",
    logo: "MI"
  },
  {
    name: "Luma AI",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "AI video and image generation for cinematic clips and visual storytelling.", fa: "تولید ویدیو و تصویر AI برای کلیپ سینمایی و روایت بصری." },
    price: 10,
    pricing: { en: "Free generations + paid plans", fa: "تولید رایگان محدود + پلن‌های پولی" },
    plan: "freemium",
    score: 83,
    jobs: ["AI Video Creator", "Visual Storyteller"],
    url: "https://lumalabs.ai",
    tags: ["video", "cinematic", "image"],
    modelType: "video",
    logo: "LU"
  },
  {
    name: "Pika",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "Text-to-video and image-to-video clips for social content and experiments.", fa: "تبدیل متن و تصویر به ویدیو برای محتوای شبکه اجتماعی و تست خلاقانه." },
    price: 10,
    pricing: { en: "Free tier + paid plans", fa: "نسخه رایگان + پلن‌های پولی" },
    plan: "freemium",
    score: 81,
    jobs: ["Short-form Video Creator", "AI Editor"],
    url: "https://pika.art",
    tags: ["video", "social", "animation"],
    modelType: "video",
    logo: "PK"
  },
  {
    name: "Replit AI",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: { en: "Build, deploy, and collaborate on code projects with AI assistance in the browser.", fa: "ساخت، انتشار و همکاری روی پروژه‌های کدنویسی با کمک AI داخل مرورگر." },
    price: 20,
    pricing: { en: "Free tier + paid plans", fa: "نسخه رایگان + پلن‌های پولی" },
    plan: "freemium",
    score: 79,
    jobs: ["Prototype Developer", "Full-stack Builder"],
    url: "https://replit.com/ai",
    tags: ["coding", "deploy", "browser"],
    modelType: "coding",
    logo: "RP"
  },
  {
    name: "Grok",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Conversational AI from xAI with real-time knowledge, reasoning, and image generation.", fa: "هوش مصنوعی گفتگومحور xAI با دانش لحظه‌ای، استدلال و تولید تصویر." },
    price: 0,
    pricing: { en: "Free with X account + paid Premium tiers", fa: "رایگان با حساب X + پلن‌های پولی Premium" },
    plan: "freemium",
    score: 90,
    jobs: ["AI Researcher", "Conversation Designer"],
    url: "https://x.ai",
    tags: ["llm", "realtime", "reasoning"],
    modelType: "multimodal",
    logo: "GK"
  },
  {
    name: "DeepSeek",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Open-weight reasoning and coding models with strong performance at low cost.", fa: "مدل‌های متن‌باز استدلال و کدنویسی با عملکرد قوی و هزینه پایین." },
    price: 0,
    pricing: { en: "Free chat + low-cost API", fa: "چت رایگان + API کم‌هزینه" },
    plan: "freemium",
    score: 91,
    jobs: ["ML Engineer", "AI Developer"],
    url: "https://www.deepseek.com",
    tags: ["llm", "open source", "coding"],
    modelType: "text",
    logo: "DS"
  },
  {
    name: "Cohere",
    category: { en: "Models and datasets", fa: "مدل و دیتاست" },
    useCase: { en: "Enterprise LLMs for search, retrieval-augmented generation, and business workflows.", fa: "مدل‌های زبانی سازمانی برای سرچ، RAG و جریان‌های کاری کسب‌وکار." },
    price: 0,
    pricing: { en: "Free trial tier + usage-based API", fa: "نسخه آزمایشی رایگان + API مصرف‌محور" },
    plan: "freemium",
    score: 84,
    jobs: ["Enterprise AI Engineer", "Search Specialist"],
    url: "https://cohere.com",
    tags: ["llm", "enterprise", "RAG"],
    modelType: "text",
    logo: "CO"
  },
  {
    name: "Meta AI",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Meta's assistant built on Llama models for chat, image generation, and creative tasks.", fa: "دستیار Meta بر پایه مدل‌های Llama برای چت، تولید تصویر و کارهای خلاقانه." },
    price: 0,
    pricing: { en: "Free across Meta apps", fa: "رایگان در اپ‌های Meta" },
    plan: "free",
    score: 87,
    jobs: ["AI Content Creator", "Conversation Designer"],
    url: "https://www.meta.ai",
    tags: ["llm", "open source", "social"],
    modelType: "multimodal",
    logo: "M"
  },
  {
    name: "Sora",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "OpenAI's text-to-video model for cinematic, realistic AI video generation.", fa: "مدل متن‌به‌ویدیو OpenAI برای تولید ویدیوی سینمایی و واقع‌گرایانه." },
    price: 20,
    pricing: { en: "Included with ChatGPT Plus/Pro plans", fa: "همراه پلن‌های ChatGPT Plus/Pro" },
    plan: "paid",
    score: 88,
    jobs: ["AI Video Creator", "Motion Designer"],
    url: "https://openai.com/sora",
    tags: ["video", "cinematic", "generation"],
    modelType: "video",
    logo: "SO"
  },
  {
    name: "Flux",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "High-fidelity open image generation models from Black Forest Labs.", fa: "مدل‌های متن‌باز تولید تصویر باکیفیت از Black Forest Labs." },
    price: 0,
    pricing: { en: "Free open models + paid API access", fa: "مدل‌های متن‌باز رایگان + دسترسی API پولی" },
    plan: "freemium",
    score: 86,
    jobs: ["AI Image Artist", "ML Engineer"],
    url: "https://blackforestlabs.ai",
    tags: ["image", "open source", "generation"],
    modelType: "image",
    logo: "FX"
  },
  {
    name: "Stability AI",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "Creators of Stable Diffusion — open models for image, video, and audio generation.", fa: "سازنده Stable Diffusion — مدل‌های متن‌باز برای تولید تصویر، ویدیو و صدا." },
    price: 0,
    pricing: { en: "Free open models + paid membership", fa: "مدل‌های متن‌باز رایگان + اشتراک پولی" },
    plan: "freemium",
    score: 85,
    jobs: ["AI Image Artist", "Generative ML Engineer"],
    url: "https://stability.ai",
    tags: ["image", "open source", "diffusion"],
    modelType: "image",
    logo: "ST"
  },
  {
    name: "Krea AI",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "Real-time AI image generation and editing with live canvas and enhancement tools.", fa: "تولید و ویرایش تصویر AI به‌صورت لحظه‌ای با بوم زنده و ابزار بهبود." },
    price: 10,
    pricing: { en: "Free daily credits + paid plans", fa: "اعتبار رایگان روزانه + پلن‌های پولی" },
    plan: "freemium",
    score: 82,
    jobs: ["AI Designer", "Visual Creator"],
    url: "https://www.krea.ai",
    tags: ["image", "realtime", "editing"],
    modelType: "image",
    logo: "KR"
  },
  {
    name: "Higgsfield",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "AI video generation focused on cinematic camera motion and social-ready clips.", fa: "تولید ویدیوی AI با تمرکز بر حرکت سینمایی دوربین و کلیپ‌های شبکه اجتماعی." },
    price: 15,
    pricing: { en: "Free credits + paid plans", fa: "اعتبار رایگان + پلن‌های پولی" },
    plan: "freemium",
    score: 80,
    jobs: ["AI Video Creator", "Social Content Producer"],
    url: "https://higgsfield.ai",
    tags: ["video", "motion", "social"],
    modelType: "video",
    logo: "HF"
  },
  {
    name: "Google Flow",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "Google's AI filmmaking tool built on Veo for generating and editing video scenes.", fa: "ابزار فیلم‌سازی AI گوگل بر پایه Veo برای تولید و ویرایش صحنه‌های ویدیو." },
    price: 20,
    pricing: { en: "Included with Google AI paid plans", fa: "همراه پلن‌های پولی Google AI" },
    plan: "paid",
    score: 83,
    jobs: ["AI Filmmaker", "Motion Designer"],
    url: "https://labs.google/flow",
    tags: ["video", "google", "filmmaking"],
    modelType: "video",
    logo: "GF"
  }
);

// ── ADDITIONAL AI TOOLS — broader, more complete catalogue ──
tools.push(
  {
    name: "Microsoft Copilot",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "Microsoft's AI assistant across Windows, Edge, and Microsoft 365 apps.", fa: "دستیار AI مایکروسافت در ویندوز، Edge و اپ‌های Microsoft 365." },
    price: 20,
    pricing: { en: "Free + Copilot Pro about $20/mo", fa: "رایگان + Copilot Pro حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 90,
    jobs: ["AI Productivity Specialist", "Automation Builder"],
    url: "https://copilot.microsoft.com",
    tags: ["writing", "office", "microsoft"],
    modelType: "assistant",
    logo: "MC"
  },
  {
    name: "Notebook LM",
    category: { en: "Research", fa: "تحقیق و سرچ" },
    useCase: { en: "Google's AI research notebook that summarizes and answers questions from your own sources.", fa: "دفترچه تحقیق AI گوگل که از منابع خودت خلاصه و پاسخ می‌سازد." },
    price: 0,
    pricing: { en: "Free", fa: "رایگان" },
    plan: "free",
    score: 87,
    jobs: ["Researcher", "Analyst"],
    url: "https://notebooklm.google.com",
    tags: ["research", "summary", "google"],
    modelType: "assistant",
    logo: "NL"
  },
  {
    name: "Leonardo AI",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "AI image generation with fine creative control, presets, and game-asset tooling.", fa: "تولید تصویر AI با کنترل خلاقانه دقیق، پریست و ابزار ساخت اسِت بازی." },
    price: 12,
    pricing: { en: "Free plan + paid from about $12/mo", fa: "پلن رایگان + پولی از حدود ۱۲ دلار ماهانه" },
    plan: "freemium",
    score: 84,
    jobs: ["AI Artist", "Game Asset Designer"],
    url: "https://leonardo.ai",
    tags: ["image", "art", "design"],
    modelType: "image",
    logo: "LA"
  },
  {
    name: "Ideogram",
    category: { en: "Image", fa: "تصویر" },
    useCase: { en: "AI image generator known for accurate text rendering inside images.", fa: "تولیدکننده تصویر AI با تخصص در نمایش دقیق متن داخل تصویر." },
    price: 8,
    pricing: { en: "Free plan + paid from about $8/mo", fa: "پلن رایگان + پولی از حدود ۸ دلار ماهانه" },
    plan: "freemium",
    score: 82,
    jobs: ["AI Artist", "Brand Designer"],
    url: "https://ideogram.ai",
    tags: ["image", "text", "design"],
    modelType: "image",
    logo: "ID"
  },
  {
    name: "HeyGen",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "AI video with realistic avatars and voice for marketing and training clips.", fa: "ویدیو AI با آواتار واقع‌گرایانه و صدا برای کلیپ بازاریابی و آموزش." },
    price: 29,
    pricing: { en: "Free plan + paid from about $29/mo", fa: "پلن رایگان + پولی از حدود ۲۹ دلار ماهانه" },
    plan: "freemium",
    score: 83,
    jobs: ["AI Video Producer", "Content Creator"],
    url: "https://www.heygen.com",
    tags: ["video", "avatar", "marketing"],
    modelType: "video",
    logo: "HG"
  },
  {
    name: "Synthesia",
    category: { en: "Video", fa: "ویدیو" },
    useCase: { en: "AI avatar video platform for corporate training and explainer content.", fa: "پلتفرم ویدیوی آواتار AI برای آموزش سازمانی و محتوای توضیحی." },
    price: 29,
    pricing: { en: "Paid from about $29/mo", fa: "پولی از حدود ۲۹ دلار ماهانه" },
    plan: "paid",
    score: 81,
    jobs: ["AI Video Producer", "L&D Specialist"],
    url: "https://www.synthesia.io",
    tags: ["video", "avatar", "training"],
    modelType: "video",
    logo: "SY"
  },
  {
    name: "Descript",
    category: { en: "Audio", fa: "صدا" },
    useCase: { en: "Edit audio and video by editing the transcript — AI voices, filler removal, and more.", fa: "ویرایش صدا و ویدیو از روی متن — صدای AI، حذف کلمات اضافه و بیشتر." },
    price: 19,
    pricing: { en: "Free plan + paid from about $19/mo", fa: "پلن رایگان + پولی از حدود ۱۹ دلار ماهانه" },
    plan: "freemium",
    score: 84,
    jobs: ["Podcast Editor", "Video Editor"],
    url: "https://www.descript.com",
    tags: ["audio", "video", "editing"],
    modelType: "audio",
    logo: "DS"
  },
  {
    name: "Udio",
    category: { en: "Audio", fa: "صدا" },
    useCase: { en: "AI music generation that turns text prompts into full songs with vocals.", fa: "تولید موسیقی AI که پرامپت متنی را به آهنگ کامل با وکال تبدیل می‌کند." },
    price: 10,
    pricing: { en: "Free plan + paid from about $10/mo", fa: "پلن رایگان + پولی از حدود ۱۰ دلار ماهانه" },
    plan: "freemium",
    score: 80,
    jobs: ["AI Music Producer", "Sound Designer"],
    url: "https://www.udio.com",
    tags: ["audio", "music", "generation"],
    modelType: "audio",
    logo: "UD"
  },
  {
    name: "Windsurf",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: { en: "AI coding IDE with an agentic assistant that edits across your whole codebase.", fa: "محیط کدنویسی AI با دستیار agentic که در کل کدبیس ویرایش می‌کند." },
    price: 15,
    pricing: { en: "Free plan + paid from about $15/mo", fa: "پلن رایگان + پولی از حدود ۱۵ دلار ماهانه" },
    plan: "freemium",
    score: 86,
    jobs: ["Software Engineer", "AI Developer"],
    url: "https://windsurf.com",
    tags: ["coding", "ide", "agent"],
    modelType: "coding",
    logo: "WS"
  },
  {
    name: "v0",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: { en: "Vercel's AI tool that generates React UI and full front-end code from prompts.", fa: "ابزار AI ورسل که از پرامپت، رابط React و کد فرانت‌اند تولید می‌کند." },
    price: 20,
    pricing: { en: "Free plan + paid from about $20/mo", fa: "پلن رایگان + پولی از حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 85,
    jobs: ["Front-End Developer", "UI Engineer"],
    url: "https://v0.dev",
    tags: ["coding", "ui", "react"],
    modelType: "coding",
    logo: "V0"
  },
  {
    name: "Lovable",
    category: { en: "Coding", fa: "کدنویسی" },
    useCase: { en: "AI app builder that turns plain descriptions into working full-stack web apps.", fa: "سازنده اپ AI که توصیف ساده را به وب‌اپ فول‌استک کاربردی تبدیل می‌کند." },
    price: 20,
    pricing: { en: "Free plan + paid from about $20/mo", fa: "پلن رایگان + پولی از حدود ۲۰ دلار ماهانه" },
    plan: "freemium",
    score: 83,
    jobs: ["Full-Stack Developer", "Indie Maker"],
    url: "https://lovable.dev",
    tags: ["coding", "app", "no-code"],
    modelType: "coding",
    logo: "LO"
  },
  {
    name: "Tability",
    category: { en: "Productivity", fa: "بهره‌وری" },
    useCase: { en: "AI-assisted goal and OKR tracking that drafts measurable objectives for teams.", fa: "پیگیری هدف و OKR با کمک AI که اهداف قابل‌اندازه‌گیری برای تیم می‌نویسد." },
    price: 12,
    pricing: { en: "Paid from about $12/mo", fa: "پولی از حدود ۱۲ دلار ماهانه" },
    plan: "paid",
    score: 76,
    jobs: ["Product Manager", "Team Lead"],
    url: "https://www.tability.io",
    tags: ["productivity", "okr", "planning"],
    modelType: "assistant",
    logo: "TB"
  },
  {
    name: "Fireflies",
    category: { en: "Productivity", fa: "بهره‌وری" },
    useCase: { en: "AI meeting assistant that records, transcribes, and summarizes calls automatically.", fa: "دستیار جلسه AI که تماس‌ها را ضبط، رونویسی و خلاصه می‌کند." },
    price: 10,
    pricing: { en: "Free plan + paid from about $10/mo", fa: "پلن رایگان + پولی از حدود ۱۰ دلار ماهانه" },
    plan: "freemium",
    score: 80,
    jobs: ["Operations Specialist", "Project Manager"],
    url: "https://fireflies.ai",
    tags: ["productivity", "meetings", "transcription"],
    modelType: "assistant",
    logo: "FF"
  },
  {
    name: "Tome",
    category: { en: "Presentations", fa: "ارائه" },
    useCase: { en: "AI presentation tool that builds polished decks and narratives from a prompt.", fa: "ابزار ارائه AI که از یک پرامپت، اسلاید و روایت حرفه‌ای می‌سازد." },
    price: 16,
    pricing: { en: "Free plan + paid from about $16/mo", fa: "پلن رایگان + پولی از حدود ۱۶ دلار ماهانه" },
    plan: "freemium",
    score: 78,
    jobs: ["Presentation Designer", "Marketer"],
    url: "https://tome.app",
    tags: ["presentations", "decks", "design"],
    modelType: "assistant",
    logo: "TM"
  },
  {
    name: "Jasper",
    category: { en: "General assistant", fa: "دستیار عمومی" },
    useCase: { en: "AI writing platform for marketing copy, campaigns, and brand-consistent content.", fa: "پلتفرم نوشتن AI برای کپی بازاریابی، کمپین و محتوای هماهنگ با برند." },
    price: 39,
    pricing: { en: "Paid from about $39/mo", fa: "پولی از حدود ۳۹ دلار ماهانه" },
    plan: "paid",
    score: 79,
    jobs: ["AI Content Specialist", "Marketing Copywriter"],
    url: "https://www.jasper.ai",
    tags: ["writing", "marketing", "content"],
    modelType: "assistant",
    logo: "JP"
  }
);

// Each tool is mapped to a representative public GitHub repo.
// Open-source tools use their own repo; closed-source products
// (ChatGPT, Claude, etc.) use their official public SDK/org repo
// — a real, live signal of developer interest in that ecosystem.
// The live 3D chart and the comparison table both read the star
// counts fetched from these repos, so the two stay aligned.
const toolRepos = {
  "ChatGPT":         "openai/openai-python",
  "Claude":          "anthropics/anthropic-sdk-python",
  "Perplexity":      "ppl-ai/api-cookbook",
  "Cursor":          "getcursor/cursor",
  "GitHub Copilot":  "github/copilot.vim",
  "Canva AI":        "canva-sdks/canva-apps-sdk-starter-kit",
  "Runway":          "runwayml/sdk-node",
  "ElevenLabs":      "elevenlabs/elevenlabs-python",
  "Hugging Face":    "huggingface/transformers",
  "Gamma":           "gamma-app/gamma-cli",
  "Zapier AI":       "zapier/zapier-platform",
  "Notion AI":       "makenotion/notion-sdk-js",
  "Gemini":          "google-gemini/cookbook",
  "Midjourney":      "midjourney/docs",
  "Adobe Firefly":   "AdobeDocs/firefly-services",
  "Suno":            "suno-ai/bark",
  "Mistral Le Chat": "mistralai/mistral-src",
  "Luma AI":         "lumalabs/luma-api-examples",
  "Pika":            "pika-org/pikascript",
  "Replit AI":       "replit/replit-ai-python",
  "Grok":            "xai-org/grok-1",
  "DeepSeek":        "deepseek-ai/DeepSeek-V3",
  "Cohere":          "cohere-ai/cohere-python",
  "Meta AI":         "meta-llama/llama-models",
  "Sora":            "openai/openai-cookbook",
  "Flux":            "black-forest-labs/flux",
  "Stability AI":    "Stability-AI/generative-models",
  "Krea AI":         "krea-ai/open-prompts",
  "Higgsfield":      "higgsfield-ai/higgsfield",
  "Google Flow":     "google-deepmind/veo",
  "Microsoft Copilot": "microsoft/copilot-studio-samples",
  "Notebook LM":     "google-gemini/cookbook",
  "Leonardo AI":     "leonardo-ai/leonardo-python-sdk",
  "Ideogram":        "ideogram-ai/ideogram-python",
  "HeyGen":          "HeyGen-Official/StreamingAvatarSDK",
  "Synthesia":       "synthesia-io/docs",
  "Descript":        "descriptinc/descript-sdk",
  "Udio":            "udio-ai/udio-api",
  "Windsurf":        "Exafunction/codeium",
  "v0":              "vercel/ai",
  "Lovable":         "lovable-dev/lovable",
  "Fireflies":       "fireflies-ai/fireflies-api",
  "Tome":            "tome-hq/tome",
  "Jasper":          "jasperai/jasper-sdk"
};

tools.forEach((tool) => {
  tool.logo ||= tool.name.slice(0, 2).toUpperCase();
  try {
    tool.logoUrl ||= `https://www.google.com/s2/favicons?domain=${new URL(tool.url).hostname}&sz=64`;
    tool.domain ||= new URL(tool.url).hostname;
  } catch {
    tool.logoUrl ||= "";
    tool.domain ||= "";
  }
  tool.modelType ||= tool.category.en.toLowerCase().includes("coding")
    ? "coding"
    : tool.category.en.toLowerCase().includes("video")
      ? "video"
      : tool.category.en.toLowerCase().includes("image")
        ? "image"
        : tool.category.en.toLowerCase().includes("audio")
          ? "audio"
          : "text";
  // GitHub repo + live-metric placeholders (filled by fetchLiveChartData)
  tool.repo = toolRepos[tool.name] || null;
  tool.stars = null;        // live: stargazers_count
  tool.forks = null;        // live: forks_count
  tool.issues = null;       // live: open_issues_count
  tool.pushedAt = null;     // live: pushed_at (ISO date of last push)
  tool.activityDays = null; // derived: days since last push
});

const aaModelSnapshot = [
  { model: "o3-mini", provider: "OpenAI", intelligence: 62.9, speed: 153.831, cost: 1.925, domain: "openai.com" },
  { model: "GPT-5.5 (xhigh)", provider: "OpenAI", intelligence: 60.2, speed: 75.1, cost: 11.25, domain: "openai.com" },
  { model: "GPT-5.3 Codex (xhigh)", provider: "OpenAI", intelligence: 54, speed: 78.15, cost: 4.81, domain: "openai.com" },
  { model: "GLM-5.1", provider: "Z AI", intelligence: 51, speed: 1.62, cost: 2.15, domain: "z.ai" },
  { model: "GPT Image 1 (high)", provider: "OpenAI", intelligence: 1128, speed: null, cost: null, domain: "openai.com", metric: "Image Editing Elo" },
  { model: "DALL·E 3", provider: "OpenAI", intelligence: 1250, speed: null, cost: null, domain: "openai.com", metric: "Text-to-Image Elo" },
  { model: "Kling 2.5 Turbo 1080p", provider: "Kuaishou KlingAI", intelligence: 1180, speed: null, cost: null, domain: "klingai.com", metric: "Text-to-Video Elo" },
  { model: "Kling 2.5 Turbo 1080p", provider: "Kuaishou KlingAI", intelligence: 1120, speed: null, cost: null, domain: "klingai.com", metric: "Image-to-Video Elo" }
];

const jobRoles = [
  {
    title: "AI Automation Specialist",
    keywords: ["zapier", "make", "automation", "excel", "api", "اتوماسیون"],
    path: {
      en: "Build workflows for businesses by connecting forms, CRM, email, sheets, and AI actions.",
      fa: "برای کسب‌وکارها workflow بساز: اتصال فرم، CRM، ایمیل، شیت و اکشن‌های AI."
    },
    tools: ["Zapier AI", "ChatGPT", "Notion AI"]
  },
  {
    title: "Prompt Engineer / AI Content Specialist",
    keywords: ["writing", "content", "prompt", "seo", "تولید محتوا", "نوشتن"],
    path: {
      en: "Design prompts, content systems, SEO briefs, brand voice guides, and reusable AI templates.",
      fa: "prompt، سیستم تولید محتوا، brief سئو، راهنمای لحن برند و تمپلیت AI بساز."
    },
    tools: ["ChatGPT", "Claude", "Perplexity"]
  },
  {
    title: "AI Frontend Developer",
    keywords: ["react", "javascript", "html", "css", "frontend", "کدنویسی"],
    path: {
      en: "Ship small AI apps, dashboards, landing pages, and API-connected prototypes.",
      fa: "اپ‌های کوچک AI، داشبورد، landing page و نمونه‌های متصل به API بساز."
    },

// ── HELPERS (used by multiple pages) ────────────────────────────────────
function escapeHtml(s){ return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }

// Fix tool logo + domain
tools.forEach(tool => {
  tool.logo  = tool.logo  || tool.name.slice(0,2).toUpperCase();
  try {
    tool.logoUrl = tool.logoUrl || `https://www.google.com/s2/favicons?domain=${new URL(tool.url).hostname}&sz=64`;
    tool.domain  = tool.domain  || new URL(tool.url).hostname;
  } catch(e) { tool.logoUrl=""; tool.domain=""; }
  tool.modelType = tool.modelType || (
    tool.category.en.toLowerCase().includes("coding") ? "coding" :
    tool.category.en.toLowerCase().includes("video")  ? "video"  :
    tool.category.en.toLowerCase().includes("image")  ? "image"  :
    tool.category.en.toLowerCase().includes("audio")  ? "audio"  : "text"
  );
  tool.repo = (typeof toolRepos !== "undefined" && toolRepos[tool.name]) || null;
  tool.stars=null; tool.forks=null; tool.pushedAt=null; tool.activityDays=null;
});
